### ISSUE TITLE
Issue with LapackUtil

### ISSUE THREAD

**Issue by hurak** [andreasvarga/MatrixEquations.jl#1]
Hi Andreas, 

first, let me express I am very pleased to see that you cannot abandon your lifetime topic and decided to contribute to Julia ecosystem. This might be a major reinforcement for the part of Julia community interested in control-related algorithms.

Second, let me inform you that I am having troubles to even start using your package. This is what I get after adding MatrixEquations.jl to my Julia 1.1:

```
julia> using MatrixEquations
[ Info: Precompiling MatrixEquations [99c1a7ee-ab34-5fd5-8076-27c950a045f4]
ERROR: LoadError: ArgumentError: Package MatrixEquations does not have LapackUtil in its dependencies:
- If you have MatrixEquations checked out for development and have
  added LapackUtil as a dependency but haven't updated your primary
  environment's manifest file, try `Pkg.resolve()`.
- Otherwise you may need to report an issue with MatrixEquations
Stacktrace:
 [1] require(::Module, ::Symbol) at ./loading.jl:836
 [2] include at ./boot.jl:326 [inlined]
 [3] include_relative(::Module, ::String) at ./loading.jl:1038
 [4] include(::Module, ::String) at ./sysimg.jl:29
 [5] top-level scope at none:2
 [6] eval at ./boot.jl:328 [inlined]
 [7] eval(::Expr) at ./client.jl:404
 [8] top-level scope at ./none:3
in expression starting at /home/hurak/.julia/packages/MatrixEquations/T51DM/src/MatrixEquations.jl:4
ERROR: Failed to precompile MatrixEquations [99c1a7ee-ab34-5fd5-8076-27c950a045f4] to /home/hurak/.julia/compiled/v1.1/MatrixEquations/1uOBF.ji.
Stacktrace:
 [1] compilecache(::Base.PkgId, ::String) at ./loading.jl:1197
 [2] _require(::Base.PkgId) at ./loading.jl:960
 [3] require(::Base.PkgId) at ./loading.jl:858
 [4] require(::Module, ::Symbol) at ./loading.jl:853
```
This must be somehow related to the package design and implementation. I am not yet sufficiently fluent with these things to advise.

**Comment by andreasvarga** [comment]
> 
> 
> Hi Andreas,
> 
> first, let me express I am very pleased to see that you cannot abandon your lifetime topic and decided to contribute to Julia ecosystem. This might be a major reinforcement for the part of Julia community interested in control-related algorithms.
> 
> Second, let me inform you that I am having troubles to even start using your package. This is what I get after adding MatrixEquations.jl to my Julia 1.1:
> 
> ```
> julia> using MatrixEquations
> [ Info: Precompiling MatrixEquations [99c1a7ee-ab34-5fd5-8076-27c950a045f4]
> ERROR: LoadError: ArgumentError: Package MatrixEquations does not have LapackUtil in its dependencies:
> - If you have MatrixEquations checked out for development and have
>   added LapackUtil as a dependency but haven't updated your primary
>   environment's manifest file, try `Pkg.resolve()`.
> - Otherwise you may need to report an issue with MatrixEquations
> Stacktrace:
>  [1] require(::Module, ::Symbol) at ./loading.jl:836
>  [2] include at ./boot.jl:326 [inlined]
>  [3] include_relative(::Module, ::String) at ./loading.jl:1038
>  [4] include(::Module, ::String) at ./sysimg.jl:29
>  [5] top-level scope at none:2
>  [6] eval at ./boot.jl:328 [inlined]
>  [7] eval(::Expr) at ./client.jl:404
>  [8] top-level scope at ./none:3
> in expression starting at /home/hurak/.julia/packages/MatrixEquations/T51DM/src/MatrixEquations.jl:4
> ERROR: Failed to precompile MatrixEquations [99c1a7ee-ab34-5fd5-8076-27c950a045f4] to /home/hurak/.julia/compiled/v1.1/MatrixEquations/1uOBF.ji.
> Stacktrace:
>  [1] compilecache(::Base.PkgId, ::String) at ./loading.jl:1197
>  [2] _require(::Base.PkgId) at ./loading.jl:960
>  [3] require(::Base.PkgId) at ./loading.jl:858
>  [4] require(::Module, ::Symbol) at ./loading.jl:853
> ```
> 
> This must be somehow related to the package design and implementation. I am not yet sufficiently fluent with these things to advise.

Hi,

This package is not yet a registered Julia package. However, I know that people succeded to download the repository and succesfully executed the tests. This is how I am working myself too (using Atom as editor and command line interface to Julia). I just uploaded a new version, adding a complete set of solvers for non-negative Lyapunov equations. I tagged this as version v0.8 (I fill there is still need for some polishing and testing on real examples). 

My suggestion is to download the zip-file with the package and unzip into a directory, say, MatrixEquation.jl. Change to this directory and enter:

using MatrixEquations

then, enter:

cd("test")

and finally: 

include("runtests.jl")

It should (hopefully) work on Julia V1.1. 

Best regards,
Andras

**Comment by andreasvarga** [comment]
Finally I succeeded to register v1.0.0, which is now reasonably complete and reasonably tested. Its installation can be done in the standard way

] add MatrixEquations

I an pondering to start another project for matrix pencil related computations (e.g., Kronecker-like forms). This would have some relevance also for matrix polynomials related computations.

Best regards,
Andreas
