### ISSUE TITLE
Documentation error of `arec`

### ISSUE THREAD

**Issue by JinraeKim** [andreasvarga/MatrixEquations.jl#10]
In the [README.md](https://github.com/andreasvarga/MatrixEquations.jl), 

> arec Solution of the continuous Riccati equations AX+XA'-XRX+Q = 0 and A'X+XA-(XB+S)R^(-1)(B'X+S')+Q = 0.

should be

> > arec Solution of the continuous Riccati equations A'X+XA-XRX+Q = 0 and A'X+XA-(XB+S)R^(-1)(B'X+S')+Q = 0.

according to the [latest docs](https://andreasvarga.github.io/MatrixEquations.jl/dev/riccati.html#MatrixEquations.arec).

**Comment by andreasvarga** [comment]
Corrected. Thanks!
