### ISSUE TITLE
Condition Matrix(T)' = Matrix(T') not fulfilled for all defined operators

### ISSUE THREAD

**Issue by andreasvarga** [andreasvarga/MatrixEquations.jl#2]
Let T be, for example, a Lyapunov operator T:X -> Y, which maps the upper triangular parts of symmetric matrices X to the upper  triangular parts of the symmetric matrices Y computed as  Y := A*X+X*A'. Similarly, the transposed operator Tt =T' maps X to Y := A'*X+X*A. Consider the example:

```
julia> A = [11 12; 21 22]
2×2 Array{Int64,2}:
 11  12
 21  22

julia> T = lyapop(A,her=true)
Linear operator
  nrow: 3
  ncol: 3
  eltype: Int64
  symmetric: false
  hermitian: false

julia> Tt = lyapop(A',her=true)
Linear operator
  nrow: 3
  ncol: 3
  eltype: Int64
  symmetric: false
  hermitian: false

julia> Matrix(T)
3×3 Array{Int64,2}:
 22  24   0
 21  33  12
  0  42  44

julia> Matrix(T')
3×3 Array{Int64,2}:
 22  42   0
 12  33  21
  0  24  44

julia> Matrix(Tt)
3×3 Array{Int64,2}:
 22  42   0
 12  33  21
  0  24  44

julia> Matrix(T)' == Matrix(T')
false

julia> Matrix(Tt)' == Matrix(Tt')
false
```

However we also have, as expected,

```
julia> Matrix(T') == Matrix(Tt)
true

julia> Matrix(Tt') == Matrix(T)
true
```

Fixing this inconsistent behaviour would be very desirable in a future release.

**Comment by dpo** [comment]
Are you defining `Matrix(op)` where `op` is a Lyapunov operator anywhere? Or are you relying on the default implementation of `Matrix()`?

**Comment by andreasvarga** [comment]
I am using the default implementation.

Dominique <notifications@github.com> schrieb am Di., 3. Dez. 2019, 01:57:

**Comment by andreasvarga** [comment]
The `Matrix(T)' == Matrix(T')` issue has been solved by determining `Matrix(T')` as `Matrix(T)' ` (not a very elegant solution I admit!)
