### ISSUE TITLE
Performance Benchmarks

### ISSUE THREAD

**Issue by azev77** [andreasvarga/MatrixEquations.jl#20]
Hi, it is common for Julia packages to share performance benchmarks in the Github readme. 
See [ParallelKmeans](https://github.com/PyDataBlog/ParallelKMeans.jl).jl or [FixedEffectModels](https://github.com/FixedEffects/FixedEffectModels.jl).jl.
Would this be possible for this package at some point?

**Comment by andreasvarga** [comment]
I have no plans to add benchmark results.
