### ISSUE TITLE
Note in the Readme/Docs

### ISSUE THREAD

**Issue by azev77** [andreasvarga/MatrixEquations.jl#21]
It may help to put something like the following in the Readme/Docs
![image](https://user-images.githubusercontent.com/7883904/184441576-c38e58d7-43e4-4172-85bc-ee0ab04b1417.png)

This can help many users bc there are different formulations of LQR with slightly different notation. 
For example, I lost hours today because in my formulation the objective had `x'Su` instead of `2x'Su`...

**Comment by andreasvarga** [comment]
This is too specific for a particular class of problems.
