### ISSUE TITLE
Algebraic equation in matrix form

### ISSUE THREAD

**Issue by TrumeAAA** [andreasvarga/MatrixEquations.jl#22]
Hi, I wanted to solve a Algebraic equation in matrix form that looks like:
![屏幕截图 2022-11-21 194159](https://user-images.githubusercontent.com/94948250/203197727-bbee5a14-290d-4588-80bb-7b567262465d.png)
![屏幕截图 2022-11-21 194226](https://user-images.githubusercontent.com/94948250/203197729-ca3c5a7d-a1b6-4e44-883f-99b31e0e48b2.png)
The equation has the form: AX=0
So I need to solve det(A)=0 with respect to k. Actually it is a Algebraic equation in matrix form, is it possible to solve it with MatrixEquations.jl ?
Note: It is easy to do it by running:
`syms k;
solution = double(solve(det(A)));
`
Any suggestion will be helpful, Thank you very much!

**Comment by andreasvarga** [comment]
The short answer is: [MatrixEquations](https://github.com/andreasvarga/MatrixEquations.jl) is not suited to solve your problem.

However, apparently you have to solve an eigenvalue problem of the form `P(k)*x = 0`, where `P(k)` is a second order polynomial matrix in the indeterminate `k,` which can be written as `P(k) = P0+k*P1+k^2*P2` with `P0, P1, P2` constant matrices. To compute the eigenvalues of such a matrix  you can try to use, for example, the function `pmeigvals` available in the [MatrixPencils](https://github.com/andreasvarga/MatrixPencils.jl) package.

**Comment by TrumeAAA** [comment]
Thanks a lot! I will try it!
