### ISSUE TITLE
Derivative of cholesky factorization

### ISSUE THREAD

**Issue by blegat** [andreasvarga/MatrixEquations.jl#23]
Given a Cholesky factorization `Q = U'U` and a symmetric matrix `dQ`, I would like to find the matrix `dU` such that `dQ = U' * dU + dU' * U`. The equation is similar to the ones of this package but does not seem to match any, or does it ?

**Comment by baggepinnen** [comment]
`arec` solves `A'X + XA - (XB+S)R^(-1)(B'X+S') + Q = 0`
so with
```julia
X = dU
A = U
Q = -dQ
R = I
B = S = 0
```
you have a match? Not sure if `B=0` is accepted though?

**Comment by blegat** [comment]
That's what I thought but the issue is that they compute a PSD solution `X` and it won't work, e.g., if `A` has eigenvalues of positive real part and `Q` is PSD (as the system is unstable and a feasible PSD `X` would give a Lyapunov function).
Here, I am looking for a nonsymmetric `X`.

**Comment by andreasvarga** [comment]
This equation has a Lyapunov-like form 

A^TX+X^TA = C

and there is no solver for it in MatrixEquations. 

However, an approach to solve this equation has been proposed in

H. W. Braden, The Equation $A\sp{T}X-X\sp{T}A=B$, Siam J. Matrix Anal. Appl. 20, 395-402, 1998. [Siam J. Matrix Anal. Appl.] 

A generalization of this equation is the Sylvester-like equation

A^TX+X^TB = C

for which a solution method is described in 

F. De Teran and Froilan M. Dopico. Consistency and efficient solution of the Sylvester
equation for ⋆-congruence. Electronic J. of Linear Algebra, 22:849–863, 2011. 

Interesting information on these equations is also provided in

COMPUTATIONAL METHODS FOR LINEAR MATRIX EQUATIONS
V. SIMONCINI
[SIAM Review](https://epubs.siam.org/journal/siread)[Vol. 58, Iss. 3 (2016)](https://epubs.siam.org/toc/siread/58/3)[10.1137/130912839](https://epubs.siam.org/doi/10.1137/130912839)

**Comment by blegat** [comment]
Thank you for the detailed answer.
I just thought that if `U` is upper triangular and we want to constraint `dU` to be upper triangular as well, there is a unique solution.
It can even be computed in-place by modifying `dQ`. See https://github.com/jump-dev/DiffOpt.jl/pull/232
I'll go over the reference to see if they mention that upper triangular case (this is in the context of the revision of https://arxiv.org/abs/2206.06135)
Indeed, the one line would work but it would not provide an upper triangular solution.

**Comment by andreasvarga** [comment]
The general solution according to

Explicit solution of the operator equation A∗X + X∗A=B
Dragan S. Djordjevic
Journal of Computational and Applied Mathematics 200 (2007) 701–704

is

`dU = U'\(0.5*dQ)+ ZU`

where Z is any skew-symmetric matrix. I wonder if there exists a skew-symmetric Z to annihilate just the lower triangular part of any given solution.

**Comment by andreasvarga** [comment]
I implemented recently two solvers for Lyapunov-like equations. I also implemented a collection of experimental solvers based on Kronecker product expansions. A new patch release will include these solvers.

**Comment by blegat** [comment]
These solve my problem, thanks!

**Comment by andreasvarga** [comment]
> Given a Cholesky factorization `Q = U'U` and a symmetric matrix `dQ`, I would like to find the matrix `dU` such that `dQ = U' * dU + dU' * U`.

For your problem, with `U` upper triangular and nonsigular, a more efficient solution method, which also ensures that `dU` is upper triangular, is the following:
```
using LinearAlgebra
n = 3
dQ = Symmetric(rand(n,n))
U = UpperTriangular(rand(n,n))
dU = 0.5*(U'\dQ)   # determine a particular solution
dUl = tril(dU/U,-1)
z = -dUl+dUl'      # determine a skew-symmetric matrix which makes dU+z*U upper triangular
dU1 = triu(dU+z*U)
norm(U'*dU1+dU1'*U-dQ)

```

**Comment by andreasvarga** [comment]
> Thank you for the detailed answer.
> I just thought that if `U` is upper triangular and we want to constraint `dU` to be upper triangular as well, there is a unique solution.
> It can even be computed in-place by modifying `dQ`. See [jump-dev/DiffOpt.jl#232](https://github.com/jump-dev/DiffOpt.jl/pull/232)
> I'll go over the reference to see if they mention that upper triangular case (this is in the context of the revision of https://arxiv.org/abs/2206.06135)
> Indeed, the one line would work but it would not provide an upper triangular solution.

I wonder if there is a working scheme to determine an upper triangular `dU` for the case when `U` is upper triangular but singular.
