### ISSUE TITLE
Routine Package Test Failure

### ISSUE THREAD

**Issue by i3s93** [andreasvarga/MatrixEquations.jl#29]
Hello,

After installing and executing the tests in package mode, I received the following error message:

![Screenshot 2024-06-30 at 6 34 58 PM](https://github.com/andreasvarga/MatrixEquations.jl/assets/31548642/a45e1a1e-8302-449b-80b6-84e944cbc282)

I also would like to mention that my particular use case does not depend on this test, but I was not sure if this error was encountered by others. Can someone else reproduce this error? For what it's worth, my current version of Julia is 1.9. Thank you in advance for reviewing my comment.

**Comment by andreasvarga** [comment]
I am closing this issue, but will reopen it if concrete information on the occured error will be provided.
