### ISSUE TITLE
usage of MatrixEquations.jl in Manifolds.jl

### ISSUE THREAD

**Issue by mateuszbaran** [andreasvarga/MatrixEquations.jl#3]
Thank you for a this useful package! In `Manifolds.jl` we recently started using `MatrixEquations.jl` for projection on the Stiefiel manifold: https://github.com/JuliaNLSolvers/Manifolds.jl/pull/49 . Since we are supporting Julia 1.0 I'm considering whether we should conditionally use your package through `Requires.jl` or maybe you could support Julia 1.0? All tests in `MatrixEquations.jl` pass for me on Julia 1.0 if I define `isnothing` (which is really simple: https://github.com/JuliaLang/julia/blob/bc82c359d4fe08750915f5db84fa83bbef063629/base/some.jl#L64 ).

**Comment by andreasvarga** [comment]
Sorry for the long delay in answering this issue (I forgot to switch on the notification feature). I uploaded a new version which should be compatible with Julia 1.0. Note that, none of the solvers is affected by the changes.

**Comment by mateuszbaran** [comment]
Thanks! We'll try it in Manifolds.jl.
